import { defineConfig } from 'astro/config';
import sitemap from '@astrojs/sitemap';
import starlight from '@astrojs/starlight';

const translated = (values) => ({
  cs: values[0],
  da: values[1],
  de: values[2],
  el: values[3],
  es: values[4],
  fi: values[5],
  fr: values[6],
  hu: values[7],
  it: values[8],
  ja: values[9],
  ko: values[10],
  nl: values[11],
  no: values[12],
  pl: values[13],
  pt: values[14],
  sv: values[15],
  tr: values[16],
  uk: values[17],
  zh: values[18],
});

const groups = [
  [
    'Start',
    'start',
    [
      'Začít',
      'Start',
      'Start',
      'Έναρξη',
      'Inicio',
      'Aloita',
      'Démarrer',
      'Kezdés',
      'Inizia',
      'はじめに',
      '시작',
      'Start',
      'Start',
      'Start',
      'Começar',
      'Start',
      'Başlangıç',
      'Початок',
      '开始',
    ],
  ],
  [
    'Install',
    'install',
    [
      'Instalace',
      'Installér',
      'Installieren',
      'Εγκατάσταση',
      'Instalar',
      'Asenna',
      'Installer',
      'Telepítés',
      'Installazione',
      'インストール',
      '설치',
      'Installeren',
      'Installer',
      'Instalacja',
      'Instalar',
      'Installera',
      'Kurulum',
      'Встановлення',
      '安装',
    ],
  ],
  [
    'Update & migrate',
    'update',
    [
      'Aktualizace a migrace',
      'Opdater og migrer',
      'Aktualisieren & migrieren',
      'Ενημέρωση και μετεγκατάσταση',
      'Actualizar y migrar',
      'Päivitä ja siirrä',
      'Mettre à jour et migrer',
      'Frissítés és migrálás',
      'Aggiornare e migrare',
      '更新と移行',
      '업데이트 및 마이그레이션',
      'Bijwerken en migreren',
      'Oppdater og migrer',
      'Aktualizacja i migracja',
      'Atualizar e migrar',
      'Uppdatera och migrera',
      'Güncelleme ve geçiş',
      'Оновлення та міграція',
      '更新与迁移',
    ],
  ],
  [
    'Configure',
    'configure',
    [
      'Konfigurace',
      'Konfigurer',
      'Konfigurieren',
      'Ρύθμιση',
      'Configurar',
      'Määritä',
      'Configurer',
      'Konfigurálás',
      'Configurazione',
      '設定',
      '구성',
      'Configureren',
      'Konfigurer',
      'Konfiguracja',
      'Configurar',
      'Konfigurera',
      'Yapılandırma',
      'Налаштування',
      '配置',
    ],
  ],
  ['PWA', 'pwa', Array(19).fill('PWA')],
  ['iOS/iPadOS', 'ios', Array(19).fill('iOS/iPadOS')],
  ['Android', 'android', Array(19).fill('Android')],
  [
    'Admin',
    'admin',
    [
      'Správa',
      'Administration',
      'Administration',
      'Διαχείριση',
      'Administración',
      'Ylläpito',
      'Administration',
      'Adminisztráció',
      'Amministrazione',
      '管理',
      '관리',
      'Beheer',
      'Administrasjon',
      'Administracja',
      'Administração',
      'Administration',
      'Yönetim',
      'Адміністрування',
      '管理',
    ],
  ],
  [
    'Integrations',
    'integrations',
    [
      'Integrace',
      'Integrationer',
      'Integrationen',
      'Ενσωματώσεις',
      'Integraciones',
      'Integraatiot',
      'Intégrations',
      'Integrációk',
      'Integrazioni',
      '連携',
      '통합',
      'Integraties',
      'Integrasjoner',
      'Integracje',
      'Integrações',
      'Integrationer',
      'Entegrasyonlar',
      'Інтеграції',
      '集成',
    ],
  ],
  [
    'Troubleshooting',
    'troubleshooting',
    [
      'Řešení potíží',
      'Fejlfinding',
      'Fehlerbehebung',
      'Αντιμετώπιση προβλημάτων',
      'Solución de problemas',
      'Vianmääritys',
      'Dépannage',
      'Hibaelhárítás',
      'Risoluzione dei problemi',
      'トラブルシューティング',
      '문제 해결',
      'Problemen oplossen',
      'Feilsøking',
      'Rozwiązywanie problemów',
      'Solução de problemas',
      'Felsökning',
      'Sorun giderme',
      'Усунення проблем',
      '故障排除',
    ],
  ],
  [
    'Reference',
    'reference',
    [
      'Referenční příručka',
      'Reference',
      'Referenz',
      'Αναφορά',
      'Referencia',
      'Viite',
      'Référence',
      'Referencia',
      'Riferimenti',
      'リファレンス',
      '참조',
      'Referentie',
      'Referanse',
      'Dokumentacja',
      'Referência',
      'Referens',
      'Referans',
      'Довідник',
      '参考',
    ],
  ],
];

export default defineConfig({
  site: 'https://docs.discvault.eu',
  integrations: [
    sitemap({
      i18n: {
        defaultLocale: 'en',
        locales: {
          en: 'en-US',
          cs: 'cs-CZ',
          da: 'da-DK',
          de: 'de-DE',
          el: 'el-GR',
          es: 'es-ES',
          fi: 'fi-FI',
          fr: 'fr-FR',
          hu: 'hu-HU',
          it: 'it-IT',
          ja: 'ja-JP',
          ko: 'ko-KR',
          nl: 'nl-NL',
          no: 'nb-NO',
          pl: 'pl-PL',
          pt: 'pt-PT',
          sv: 'sv-SE',
          tr: 'tr-TR',
          uk: 'uk-UA',
          zh: 'zh-CN',
        },
      },
    }),
    starlight({
      title: 'DiscVault Docs',
      description: 'Install, use, and operate DiscVault.',
      logo: { src: './src/assets/discvault-logo.svg', alt: 'DiscVault' },
      favicon: '/brand/discvault-icon.svg',
      social: [
        {
          icon: 'github',
          label: 'GitHub',
          href: 'https://github.com/Flux76HQ/docs.discvault.eu',
        },
      ],
      editLink: { baseUrl: 'https://github.com/Flux76HQ/docs.discvault.eu/edit/main/' },
      customCss: ['./src/styles/font.css', './src/styles/tokens.css', './src/styles/custom.css'],
      components: {
        Head: './src/components/Head.astro',
        PageTitle: './src/components/BreadcrumbPageTitle.astro',
        Footer: './src/components/Footer.astro',
      },
      locales: {
        root: { label: 'English', lang: 'en' },
        cs: { label: 'Čeština', lang: 'cs', builtInLocale: 'cs' },
        da: { label: 'Dansk', lang: 'da', builtInLocale: 'da' },
        de: { label: 'Deutsch', lang: 'de', builtInLocale: 'de' },
        el: { label: 'Ελληνικά', lang: 'el' },
        es: { label: 'Español', lang: 'es', builtInLocale: 'es' },
        fi: { label: 'Suomi', lang: 'fi', builtInLocale: 'fi' },
        fr: { label: 'Français', lang: 'fr', builtInLocale: 'fr' },
        hu: { label: 'Magyar', lang: 'hu', builtInLocale: 'hu' },
        it: { label: 'Italiano', lang: 'it', builtInLocale: 'it' },
        ja: { label: '日本語', lang: 'ja', builtInLocale: 'ja' },
        ko: { label: '한국어', lang: 'ko', builtInLocale: 'ko' },
        nl: { label: 'Nederlands', lang: 'nl', builtInLocale: 'nl' },
        no: { label: 'Norsk', lang: 'no', builtInLocale: 'nb' },
        pl: { label: 'Polski', lang: 'pl', builtInLocale: 'pl' },
        pt: { label: 'Português', lang: 'pt', builtInLocale: 'pt' },
        sv: { label: 'Svenska', lang: 'sv', builtInLocale: 'sv' },
        tr: { label: 'Türkçe', lang: 'tr', builtInLocale: 'tr' },
        uk: { label: 'Українська', lang: 'uk', builtInLocale: 'uk' },
        zh: { label: '中文', lang: 'zh', builtInLocale: 'zh-CN' },
      },
      sidebar: groups.map(([label, directory, labels]) => ({
        label,
        translations: translated(labels),
        autogenerate: { directory },
      })),
    }),
  ],
});
